name: Publish Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docker:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set registry environment variable
        run: echo "REGISTRY=ghcr.io" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        id: docker-login
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build 和 push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:latest
